/* ConLang Generator UI patch — v0.8.1 */
(() => {
  'use strict';
  const VERSION='0.8.1';
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function styles(){if($('ui-patch-v081'))return;const s=document.createElement('style');s.id='ui-patch-v081';s.textContent='.base-parameters{margin-top:16px}.base-parameters-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.base-parameters .param-group{background:var(--panel2);border:1px solid var(--line);border-radius:8px;padding:11px}.base-parameters .param-title{font-size:11px;text-transform:uppercase;letter-spacing:.04em;color:var(--accent);margin-bottom:7px}.base-parameters .param-value{color:var(--text);line-height:1.5}';document.head.appendChild(s)}
  function tab(){let t=document.querySelector('.tab[data-tab="samples"]'),p=$('samples');if(t&&p)return p;const tabs=document.querySelector('.tabs'),d=tabs?.querySelector('.tab[data-tab="dictionary"]');t=document.createElement('button');t.type='button';t.className='tab';t.dataset.tab='samples';t.setAttribute('aria-selected','false');t.textContent='Sample Sentences';if(d)d.insertAdjacentElement('afterend',t);else tabs?.appendChild(t);p=document.createElement('section');p.id='samples';p.className='tab-panel';p.innerHTML='<main><div id="samples-output" class="result empty">Generate a language to populate the sample sentences.</div></main>';document.querySelector('#generator')?.insertAdjacentElement('afterend',p);t.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-selected','false')});document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');t.setAttribute('aria-selected','true');p.classList.add('active')});return p}
  function val(id){const e=$(id);if(!e)return'';return e.tagName==='SELECT'?[...e.selectedOptions].map(x=>x.value).filter(Boolean).join(', '):e.value||''}
  function params(){const b=$('generation-output');if(!b)return;let c=b.querySelector('.base-parameters');if(!c){c=document.createElement('div');c.className='card base-parameters';b.appendChild(c)}const g=[['Semantic profile',[['Region',val('region')||'Any'],['Culture',val('culture')||'Any'],['Biome',val('biome')||'Any'],['Temporal setting',val('temporal_setting')||'Any'],['Tags',val('tags')||'Any']]],['Phonology',[['Vowels',$('vowels')?.selectedOptions?.[0]?.textContent||''],['Consonants',$('consonants')?.selectedOptions?.[0]?.textContent||''],['Mean syllables',$('mean')?.value||'']]],['Morphosyntax',[['Word order',val('word-order')],['Morphology',$('morphology')?.selectedOptions?.[0]?.textContent||''],['Adjective position',$('adj-position')?.selectedOptions?.[0]?.textContent||''],['Articles',$('articles')?.selectedOptions?.[0]?.textContent||''],['Plural',$('plural')?.selectedOptions?.[0]?.textContent||''],['Grammatical relations',$('relations')?.selectedOptions?.[0]?.textContent||'']]]];c.innerHTML='<h3>Language parameters</h3><div class="base-parameters-grid">'+g.map(([t,a])=>'<div class="param-group"><div class="param-title">'+esc(t)+'</div>'+a.map(([k,v])=>'<div style="margin:4px 0"><span style="color:var(--muted)">'+esc(k)+':</span> <span class="param-value">'+esc(v)+'</span></div>').join('')+'</div>').join('')+'</div>'}
  function move(){const p=tab(),o=$('generation-output'),t=$('samples-output');if(!o||!t)return;const f=o.querySelector('.sample-frame');if(f){t.innerHTML='';t.appendChild(f)}params()}
  function init(){styles();tab();const o=$('generation-output');if(o){new MutationObserver(()=>requestAnimationFrame(move)).observe(o,{childList:true,subtree:true})}move();const h=document.querySelector('header h1');if(h){let b=h.querySelector('.version-badge');if(!b){b=document.createElement('span');b.className='chip version-badge';b.style.marginLeft='8px';h.appendChild(b)}b.textContent='v'+VERSION}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();