name: Update index version

on:
  push:
    paths:
      - '.github/workflows/bump-index-version.yml'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update index version
        run: sed -i 's/v0.11.4/v0.11.8/g' index.html

      - name: Commit and remove workflow
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add index.html
          git rm .github/workflows/bump-index-version.yml
          git commit -m 'Bump index version to 0.11.8'
          git push
